### ISSUE TITLE
mp3 and youtube audio transcription does not work

### ISSUE THREAD

**Issue by SalimzianovBulat** [mimbres/YourMT3#16] opened 2024-11-24 10:37 UTC
I am trying to convert mp3 file or youtube url from colab, i am using your function called: process_audio

After running this code: process_audio("/content/sonata.mp3")  I get this output and error

⏰ converting audio: 0m 0s 455.34ms
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-bc87a7121749>](https://localhost:8080/#) in <cell line: 1>()
----> 1 process_audio("/content/sonata.mp3")

22 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py](https://localhost:8080/#) in forward(self, hidden_states, mask, key_value_states, position_bias, past_key_value, layer_head_mask, query_length, use_cache, output_attentions, cache_position)
    523             key_length = key_states.shape[-2]
    524             # cache position is 0-indexed so we add 1 to get the real length of queries (aka with past)
--> 525             real_seq_length = query_length if query_length is not None else cache_position[-1] + 1
    526             if not self.has_relative_attention_bias:
    527                 position_bias = torch.zeros(

TypeError: 'NoneType' object is not subscriptable

how can i fix this problem, it was working correcly month ago but now something changed ( maybe some python libraries have changed ) 

I have run the same code ( notebook ) in kaggle notebook and there it worked correctly, was surprised by that but actually i could not found difference between lib versions or other code differences

Can someone help because your official notebook ( link "colab"  on your github) seems not to be working correctly

**Comment by mimbres** [comment] 2024-11-28 22:58
@SalimzianovBulat I think this is a duplicate of #15

**Closed as completed by mimbres** 2024-11-28 22:58 UTC
