### ISSUE TITLE
no pre_coder in 'YPTF.MoE+Multi (noPS)'

### ISSUE THREAD

**Issue by kaiyolau** [mimbres/YourMT3#18] opened 2024-12-18 23:46 UTC
Thanks for sharing the fantastic demo!

When I was running the collab demo using 'YPTF.MoE+Multi (noPS)', I encountered this error:
```bash
standard_env/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
TypeError: 'NoneType' object is not callable
```

on further inspection, I found that that the precoder is empty. Specifically:
```python
model.pre_coder
```

gives me:

```
Sequential(
  (0): None
)
```

Any help would be greatly appreciated!

**Comment by kaiyolau** [comment] 2024-12-19 00:08
Just shutdown the kernel and re-run again, it works!

**Comment by mimbres** [comment] 2024-12-20 15:36
@kaiyolau Duplicate of #15

**Closed as completed by mimbres** 2024-12-20 15:36 UTC
